# Generated by Django 3.2 on 2021-05-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
